import streamlit as st
import pandas as pd
import json
import os
import sys
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go
from PIL import Image
import io

# PDF generation imports
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors

# Add current directory to path
sys.path.insert(0, ".")

# Import your modules
import blood_report_parser
from model1_parameter_interpreter import classify
from model2_pattern_engine import assess_risks_from_model1
import ollama_health_analysis
from ollama_health_analysis import ollama_synthesize_findings, ollama_generate_recommendations

# Page configuration
st.set_page_config(
    page_title="AI Health Diagnosis System",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS (your existing CSS + new styles)
st.markdown("""
<style>
.main-header {
    font-size: 2.5rem;
    color: #1f77b4;
    text-align: center;
    margin-bottom: 2rem;
}
.risk-high {
    border-left: 5px solid #f44336;
    padding: 10px;
    margin: 10px 0;
    color: #f0f2f6;
}
.risk-medium {
    border-left: 5px solid #ff9800;
    padding: 10px;
    margin: 10px 0;
    color: #f0f2f6;
}
.risk-low {
    border-left: 5px solid #4caf50;
    padding: 10px;
    margin: 10px 0;
    color: #f0f2f6;
}
.parameter-card {
    background-color: #262730;
    border-radius: 10px;
    padding: 15px;
    margin: 10px 0;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    color: #ffffff;
    line-height: 1.6;
}
.image-upload-container {
    border: 2px dashed #cccccc;
    border-radius: 10px;
    padding: 20px;
    text-align: center;
    margin: 10px 0;
}
</style>
""", unsafe_allow_html=True)

# Load parameter ranges
@st.cache_data
def load_parameter_ranges():
    try:
        with open("parameter_ranges.json", 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        st.error("Parameter ranges file not found. Please ensure parameter_ranges.json exists.")
        return {}

def main():
    st.markdown('<h1 class="main-header">🏥 AI Health Diagnosis System</h1>', unsafe_allow_html=True)
    
    # Sidebar
    st.sidebar.title("📋 Patient Information")
    
    # Patient demographics
    patient_age = st.sidebar.number_input("Age", min_value=1, max_value=120, value=45)
    patient_gender = st.sidebar.selectbox("Gender", ["Male", "Female", "Other"])
    activity_level = st.sidebar.selectbox("Activity Level", ["Low", "Moderate", "High"])
    
    st.sidebar.markdown("---")
    
    # File upload options - UPDATED
    st.sidebar.title("📄 Upload Report")
    
    # Upload type selection
    upload_type = st.sidebar.radio(
        "Select file type:",
        ["PDF Document", "Image File (JPG/PNG)", "Manual Input"]
    )
    
    if upload_type == "PDF Document":
        uploaded_file = st.sidebar.file_uploader("Choose a PDF file", type="pdf")
        if uploaded_file is not None:
            process_uploaded_pdf(uploaded_file, patient_age, patient_gender, activity_level)
    
    elif upload_type == "Image File (JPG/PNG)":
        uploaded_image = st.sidebar.file_uploader(
            "Choose an image file", 
            type=["jpg", "jpeg", "png", "bmp", "tiff"]
        )
        if uploaded_image is not None:
            process_uploaded_image(uploaded_image, patient_age, patient_gender, activity_level)
    
    elif upload_type == "Manual Input":
        process_manual_input(patient_age, patient_gender, activity_level)
    
    else:
        show_welcome_page()

def show_welcome_page():
    st.markdown("""
    ## Welcome to AI Health Diagnosis System
    
    This system analyzes blood test reports and provides:
    - 🔍 **Parameter Classification** using AI Model 1
    - ⚠️ **Risk Assessment** with demographic context using AI Model 2  
    - 📋 **Clinical Summary** generated by Ollama LLM
    - 💡 **Health Recommendations** personalized to your profile
    
    ### How to Use:
    1. **Upload a PDF** blood report, OR
    2. **Upload an Image** of your lab report (JPG/PNG), OR
    3. **Enter values manually** using the manual input option
    4. Fill in your demographic information (age, gender, activity level)
    5. Get instant AI-powered health insights!
    
    ### Supported File Types:
    - **PDF Documents** (.pdf)
    - **Image Files** (.jpg, .jpeg, .png, .bmp, .tiff)
    - **Manual Entry** (web form)
    
    ### Features:
    - Multi-modal AI analysis pipeline
    - OCR text extraction from images
    - Real-time risk scoring
    - Personalized recommendations
    - **📥 PDF Report Download**
    - Visual data representation
    """)
    
    # Show sample analysis
    st.markdown("### 📊 Sample Analysis Preview")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.metric("Risk Level", "MEDIUM", "↗️ 6/10")
    with col2:
        st.metric("Abnormal Parameters", "3", "🔍")
    with col3:
        st.metric("Recommendations", "6", "💡")

def process_uploaded_pdf(uploaded_file, patient_age, patient_gender, activity_level):
    """Process uploaded PDF file"""
    st.header("📄 Processing Uploaded PDF Report")
    
    with st.spinner("Extracting text from PDF..."):
        # Save uploaded file
        with open("temp_report.pdf", "wb") as f:
            f.write(uploaded_file.getbuffer())
        
        try:
            # Extract text
            raw_text = blood_report_parser.extract_text("temp_report.pdf")
            st.success("✅ Text extracted successfully!")
            
            # Show extracted text preview
            with st.expander("📝 View Extracted Text"):
                st.text(raw_text[:500] + "..." if len(raw_text) > 500 else raw_text)
            
            # Process text
            process_analysis(raw_text, patient_age, patient_gender, activity_level)
            
        except Exception as e:
            st.error(f"❌ Error processing PDF: {str(e)}")
        finally:
            # Clean up temp file
            if os.path.exists("temp_report.pdf"):
                os.remove("temp_report.pdf")

def process_uploaded_image(uploaded_image, patient_age, patient_gender, activity_level):
    """Process uploaded image file using OCR"""
    st.header("🖼️ Processing Uploaded Image Report")
    
    # Display the uploaded image
    image = Image.open(uploaded_image)
    
    col1, col2 = st.columns([1, 2])
    with col1:
        st.image(image, caption="Uploaded Report", use_column_width=True)
    
    with col2:
        st.info("""
        **Image Processing Tips:**
        - Ensure good lighting and clear text
        - Avoid glare or shadows
        - Hold camera steady
        - Make sure text is not blurry
        """)
    
    with st.spinner("Extracting text from image using OCR..."):
        try:
            # Save uploaded image
            temp_image_path = "temp_image.png"
            image.save(temp_image_path)
            
            # Extract text using OCR
            raw_text = blood_report_parser.extract_text(temp_image_path)
            
            if raw_text.strip():
                st.success("✅ Text extracted successfully from image!")
                
                # Show extracted text preview
                with st.expander("📝 View Extracted Text from Image"):
                    st.text(raw_text[:500] + "..." if len(raw_text) > 500 else raw_text)
                
                # Process the extracted text
                process_analysis(raw_text, patient_age, patient_gender, activity_level)
            else:
                st.error("❌ No readable text found in image. Please try:")
                st.markdown("""
                - A clearer, higher resolution image
                - Better lighting
                - Ensuring text is not handwritten
                - Using manual input instead
                """)
                
        except Exception as e:
            st.error(f"❌ Error processing image: {str(e)}")
            st.info("💡 Try using manual input if OCR fails")
        finally:
            # Clean up temp file
            if os.path.exists(temp_image_path):
                os.remove(temp_image_path)

def process_manual_input(patient_age, patient_gender, activity_level):
    """Process manual parameter input"""
    st.header("📝 Manual Parameter Input")
    
    # Load parameter ranges
    ranges = load_parameter_ranges()
    
    if not ranges:
        return
    
    # Create input form
    with st.form("manual_input_form"):
        st.subheader("Enter Blood Test Values")
        
        param_values = {}
        cols = st.columns(2)
        
        for i, (param, range_info) in enumerate(ranges.items()):
            col = cols[i % 2]
            
            with col:
                param_display = param.replace('_', ' ').title()
                unit = range_info.get('unit', '')
                normal_range = f"{range_info.get('min', 'N/A')} - {range_info.get('max', 'N/A')}"
                
                value = st.number_input(
                    f"{param_display} ({unit})",
                    min_value=0.0,
                    help=f"Normal range: {normal_range}",
                    key=f"param_{param}"
                )
                
                if value > 0:
                    param_values[param] = value
        
        submitted = st.form_submit_button("🔍 Analyze Results")
        
        if submitted and param_values:
            # Create validated params format
            validated_params = param_values
            
            # Process analysis
            process_analysis_from_params(validated_params, patient_age, patient_gender, activity_level)

def process_analysis(raw_text, patient_age, patient_gender, activity_level):
    """Process analysis from extracted text"""
    
    # Extract and validate parameters
    with st.spinner("Extracting parameters..."):
        params = blood_report_parser.extract_parameters(raw_text)
        validated_params = blood_report_parser.validate(params)
    
    if not validated_params:
        st.error("❌ No valid parameters found in the report.")
        return
    
    st.success(f"✅ Extracted {len(validated_params)} parameters")
    
    # Process the validated parameters
    process_analysis_from_params(validated_params, patient_age, patient_gender, activity_level)

def process_analysis_from_params(validated_params, patient_age, patient_gender, activity_level):
    """Process analysis from validated parameters"""
    
    # Load ranges
    ranges = load_parameter_ranges()
    
    # Model 1: Parameter Classification
    st.header("Parameter Classification")
    
    classification_results = {}
    for param, value in validated_params.items():
        if value is not None and param in ranges:
            status = classify(param, value, ranges)
            classification_results[param] = {"value": value, "status": status}
    
    # Display parameters table
    display_parameters_table(classification_results)
    
    # Model 2: Risk Assessment
    st.header("Risk Assessment")
    
    risk_assessment = assess_risks_from_model1(
        classification_results, 
        age=patient_age, 
        gender=patient_gender
    )
    
    # Display risk assessment
    display_risk_assessment(risk_assessment, patient_age, patient_gender)
    
    # Model 3: Clinical Synthesis
    st.header("Clinical Synthesis & Recommendations")
    
    with st.spinner("Generating clinical summary with Ollama..."):
        clinical_summary = ollama_synthesize_findings(
            classification_results,
            risk_assessment,
            user_context={"age": patient_age, "gender": patient_gender}
        )
    
    # Display clinical summary
    st.subheader("📋 Clinical Summary")
    st.markdown(f"""
    <div class="parameter-card">
    {clinical_summary.replace(chr(10), '<br>')}
    </div>
    """, unsafe_allow_html=True)
    
    # Generate recommendations
    with st.spinner("Generating personalized recommendations..."):
        abnormal_params = [f"{k} {v['status']}" for k, v in classification_results.items() 
                          if v.get('status') != 'Normal']
        
        recommendations = ollama_generate_recommendations(
            clinical_summary,
            abnormal_params,
            risk_assessment["risk_level"],
            user_context={
                "age": patient_age, 
                "gender": patient_gender, 
                "activity_level": activity_level.lower()
            }
        )
    
    # Display recommendations
    display_recommendations(recommendations)
    
    # Generate downloadable reports
    generate_reports(classification_results, risk_assessment, clinical_summary, recommendations, patient_age, patient_gender, activity_level)

def display_parameters_table(classification_results):
    """Display parameters in a nice table with color coding"""
    
    if not classification_results:
        st.warning("No parameters to display.")
        return
    
    # Create DataFrame
    data = []
    for param, info in classification_results.items():
        data.append({
            'Parameter': param.replace('_', ' ').title(),
            'Value': info['value'],
            'Status': info['status'],
            'Status_Color': get_status_color(info['status'])
        })
    
    df = pd.DataFrame(data)
    
    # Display with color coding
    for _, row in df.iterrows():
        col1, col2, col3 = st.columns([2, 1, 1])
        
        with col1:
            st.write(f"**{row['Parameter']}**")
        with col2:
            st.write(f"{row['Value']}")
        with col3:
            status_color = row['Status_Color']
            st.markdown(f'<span style="color: {status_color}; font-weight: bold">{row["Status"]}</span>', 
                       unsafe_allow_html=True)

def get_status_color(status):
    """Get color for parameter status"""
    if status == "Normal":
        return "#4caf50"  # Green
    elif "High" in status:
        return "#f44336"  # Red
    elif "Low" in status:
        return "#ff9800"  # Orange
    else:
        return "#2196f3"  # Blue

def display_risk_assessment(risk_assessment, patient_age, patient_gender):
    """Display risk assessment with visualizations"""
    
    # Risk level card
    risk_level = risk_assessment['risk_level']
    risk_score = risk_assessment['risk_score']
    
    if risk_level == "HIGH" or risk_level == "CRITICAL":
        risk_class = "risk-high"
    elif risk_level == "MODERATE":
        risk_class = "risk-medium"
    else:
        risk_class = "risk-low"
    
    st.markdown(f"""
    <div class="{risk_class}">
    <h3>Risk Level: {risk_level}</h3>
    <p><strong>Risk Score:</strong> {risk_score}/10</p>
    <p><strong>Patient:</strong> {patient_age}-year-old {patient_gender}</p>
    </div>
    """, unsafe_allow_html=True)
    
    # Risk gauge chart
    fig = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = risk_score,
        domain = {'x': [0, 1], 'y': [0, 1]},
        title = {'text': "Risk Score"},
        gauge = {
            'axis': {'range': [None, 10]},
            'bar': {'color': "darkblue"},
            'steps': [
                {'range': [0, 3], 'color': "lightgreen"},
                {'range': [3, 7], 'color': "yellow"},
                {'range': [7, 10], 'color': "red"}
            ],
            'threshold': {
                'line': {'color': "red", 'width': 4},
                'thickness': 0.75,
                'value': 8
            }
        }
    ))
    
    st.plotly_chart(fig, use_container_width=True)
    
    # Identified risks
    st.subheader("🎯 Identified Health Risks")
    for i, risk in enumerate(risk_assessment['identified_risks'][:5], 1):
        st.write(f"{i}. {risk}")

def display_recommendations(recommendations):
    """Display recommendations in organized categories"""
    
    st.subheader("💡 Personalized Health Recommendations")
    
    # Group by category
    categories = {}
    for rec in recommendations:
        cat = rec['category'].upper()
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(rec['text'])
    
    # Display by category
    for category, recs in categories.items():
        with st.expander(f"📌 {category} ({len(recs)} recommendations)"):
            for i, rec in enumerate(recs, 1):
                st.write(f"{i}. {rec}")

def generate_pdf_report(classification_results, risk_assessment, clinical_summary, recommendations, patient_age, patient_gender, activity_level):
    """Generate PDF report using ReportLab"""
    
    # Create a BytesIO buffer
    buffer = io.BytesIO()
    
    # Create the PDF document
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f77b4'),
        alignment=1,  # Center
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#333333'),
        spaceBefore=20,
        spaceAfter=10
    )
    
    # Build the PDF content
    story = []
    
    # Title
    story.append(Paragraph("🏥 Health Diagnosis Report", title_style))
    story.append(Spacer(1, 20))
    
    # Patient Information
    story.append(Paragraph("Patient Information", heading_style))
    patient_data = [
        ["Age:", f"{patient_age} years"],
        ["Gender:", patient_gender],
        ["Activity Level:", activity_level],
        ["Report Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Risk Level:", risk_assessment['risk_level']],
        ["Risk Score:", f"{risk_assessment['risk_score']}/10"]
    ]
    
    patient_table = Table(patient_data, colWidths=[2*inch, 3*inch])
    patient_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(patient_table)
    story.append(Spacer(1, 20))
    
    # Lab Results
    story.append(Paragraph("Laboratory Results", heading_style))
    
    lab_data = [["Parameter", "Value", "Status"]]
    for param, info in classification_results.items():
        lab_data.append([
            param.replace('_', ' ').title(),
            str(info['value']),
            info['status']
        ])
    
    lab_table = Table(lab_data, colWidths=[2*inch, 1*inch, 1*inch])
    lab_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(lab_table)
    story.append(Spacer(1, 20))
    
    # Clinical Summary
    story.append(Paragraph("Clinical Summary", heading_style))
    # Clean the clinical summary for PDF
    clean_summary = clinical_summary.replace('•', '* ').replace('\n', '<br/>')
    story.append(Paragraph(clean_summary, styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Recommendations
    story.append(Paragraph("Health Recommendations", heading_style))
    
    for i, rec in enumerate(recommendations[:8], 1):  # Limit to 8 recommendations
        rec_text = f"{i}. [{rec['category'].upper()}] {rec['text']}"
        story.append(Paragraph(rec_text, styles['Normal']))
        story.append(Spacer(1, 6))
    
    # Build PDF
    doc.build(story)
    
    # Get the value of the BytesIO buffer
    buffer.seek(0)
    return buffer

def generate_reports(classification_results, risk_assessment, clinical_summary, recommendations, patient_age, patient_gender, activity_level):
    """Generate downloadable reports"""
    
    st.header("📄 Download Reports")
    
    # Create report data
    report_data = {
        "patient_demographics": {
            "age": patient_age,
            "gender": patient_gender,
            "activity_level": activity_level,
            "timestamp": datetime.now().isoformat()
        },
        "lab_results": classification_results,
        "risk_assessment": {
            "level": risk_assessment['risk_level'],
            "score": risk_assessment['risk_score'],
            "identified_risks": risk_assessment['identified_risks']
        },
        "clinical_summary": clinical_summary,
        "recommendations": recommendations
    }
    
    # Create downloadable files
    col1, col2, col3 = st.columns(3)
    
    with col1:
        # JSON report
        json_report = json.dumps(report_data, indent=2, default=str)
        st.download_button(
            label="📥 Download JSON Report",
            data=json_report,
            file_name=f"health_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
            mime="application/json"
        )
    
    with col2:
        # Text summary
        text_report = f"""HEALTH ANALYSIS REPORT
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

PATIENT INFORMATION:
Age: {patient_age}
Gender: {patient_gender}
Activity Level: {activity_level}
Risk Level: {risk_assessment['risk_level']}
Risk Score: {risk_assessment['risk_score']}/10

CLINICAL SUMMARY:
{clinical_summary}

TOP RECOMMENDATIONS:
"""
        for i, rec in enumerate(recommendations[:5], 1):
            text_report += f"{i}. [{rec['category'].upper()}] {rec['text']}\n"
        
        st.download_button(
            label="📄 Download Text Report",
            data=text_report,
            file_name=f"health_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain"
        )
    
    with col3:
        # PDF report
        try:
            pdf_buffer = generate_pdf_report(
                classification_results, risk_assessment, clinical_summary, 
                recommendations, patient_age, patient_gender, activity_level
            )
            
            st.download_button(
                label="📑 Download PDF Report",
                data=pdf_buffer.getvalue(),
                file_name=f"health_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
                mime="application/pdf"
            )
        except Exception as e:
            st.error(f"PDF generation failed: {str(e)}")
            st.info("JSON and Text reports are still available above.")

if __name__ == "__main__":
    main()